name: PHP

on: ["push", "pull_request", "workflow_dispatch"]

jobs:
  build_and_test:
    name: Build and test web3.php with ${{ matrix.php-version }}
    strategy:
      matrix:
        php-version: ["7.3", "7.4", "8.0", "8.1", "8.2"]

    runs-on: ubuntu-latest

    steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
          php-version: ${{ matrix.php-version }}

    - name: PHP version
      run: |
        php --version

    - name: Install nodejs and ganache-cli
      run: |
        sudo apt-get update -y
        sudo apt-get install -y nodejs
        sudo npm install -g ganache

    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ matrix.php-version }}-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-${{ matrix.php-version }}-

    - name: Install dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Run test suite
      run: sudo scripts/test.sh
